A tabela deverá ser dividida em 3
- homens e mulheres por região com curso superior
- homens e mulheres por região com curso nas áreas de Ciência, Tecnologia, Engenharias e Matemática
- homens e mulheres por região com curso nas áreas de Educação, Serviços pessoais, Saúde e Bem-estar    
Utilize a função describe e apresente as estatísticas das 3 tabelas que você criou.

In [3]:
# No terminal, uma vez: python -m pip install openpyxl pandas
import pandas as pd
import openpyxl

path = r"C:\Users\Leonardo Melo\Desktop\Pytom(Jenaina)\Repositorio-GitHub\Lscm_Analise_de_Dados\Atv3_TODO\Tabela_3_Areas_gerais_de_formacao_na_graduacao.xlsx"

In [ ]:
#Organizando o Exel--------------------------------------------------------------
tbBruta = pd.read_excel(path, header=None)
tbBruta.columns = [ #renomendo colunas
    "Estado",
    "Total TODOS",
    "H-Geral",
    "M-Geral",
    "Total-Exatas",
    "H-Exatas",
    "M-Exatas",
    "Total Duração-Serviço",
    "H-Duração",
    "M-Duração"
]
tbBruta = tbBruta.iloc[3:36]
#Para a parte final da atividade, é nescessário que eu use o desbribe, mas ele precisa que os valores da tabela toda sejam usaveis como números
#por tanto, já de começo, devo converter a tabela toda(menos estados) pra numero
#Importante: para modificar os valores retidos nas colunas uso o APPLY()
#ou seja, para mudar tudo, devo usar o .iloc para acessar todas as colunas(menos estado)
colPresente = ["Total TODOS", "H-Geral", "M-Geral","Total-Exatas", "H-Exatas", "M-Exatas","Total Duração-Serviço", "H-Duração", "M-Duração"]
tbBruta[colPresente] = tbBruta[colPresente].apply(pd.to_numeric)

<class 'pandas.DataFrame'>

In [50]:
#Questão 1--------------------------------------------------------------
#Homens e mulheres por região com curso superior
q1 = tbBruta
q1 = q1.iloc[4:9] #Limitando as regiões
#tbBruta.loc[linha,coluna]
q1 = q1.loc[:,'Estado':'M-Geral'] #ou tbBruta[['Estado','Total TODOS','H-Geral','M-Geral']]

In [ ]:
#Questão 2--------------------------------------------------------------
#homens e mulheres por região com curso nas áreas de Ciência, Tecnologia, Engenharias e Matemática
q2 = tbBruta
q2 = q2.iloc[4:9]
q2 = q2[['Estado','Total-Exatas','H-Exatas','M-Exatas']]

In [56]:
#Questão 3--------------------------------------------------------------
#Homens e mulheres por região com curso nas áreas de Educação, Serviços pessoais, Saúde e Bem-estar 
q3 = tbBruta
q3 = q3.iloc[4:9]   
q3 = q3[['Estado','Total Duração-Serviço','H-Duração','M-Duração']]
q3

         Estado Total Duração-Serviço H-Duração M-Duração
4         Norte                599785    141169    458616
5      Nordeste               1822087    363905   1458181
6       Sudeste               3652397    768288   2884108
7           Sul               1256291    248574   1007718
8  Centro-Oeste                749148    156048    593101

In [ ]:
#Questão 4--------------------------------------------------------------
#Utilize a função describe e apresente as estatísticas das 3 tabelas que você criou.
#colocar display antes do discribe faz com que cada questão apareça individualmetne, pois o jupter processa tudo menos o último comando
display(q1.describe())
display(q2.describe())
display(q3.describe())

       Estado  Total TODOS  H-Geral  M-Geral
count       5            5        5        5
unique      5            5        5        5
top     Norte      1525166   590558   934609
freq        1            1        1        1

       Estado  Total-Exatas  H-Exatas  M-Exatas
count       5             5         5         5
unique      5             5         5         5
top     Norte        209657    133055     76601
freq        1             1         1         1

       Estado  Total Duração-Serviço  H-Duração  M-Duração
count       5                      5          5          5
unique      5                      5          5          5
top     Norte                 599785     141169     458616
freq        1                      1          1          1