Agora responda:
- Quantas horas mulheres pretas trabalham a mais que mulheres brancas em Minas Gerais?(FEITO)
- Quantas horas mulheres pretas trabalham a mais que homens brancos no Brasil?
- Quantas horas mulheres pretas trabalham a mais que mulheres brancas no Amapá?
- Quantas horas mulheres pretas trabalham a mais que mulheres brancas no Paraná?
- Quantas horas mulheres pretas trabalham a mais que mulheres brancas por região?

In [3]:
# No terminal, uma vez: python -m pip install xlrd pandas
import pandas as pd

caminho = r"H:\Escola\Pytom(Jenaina)\Repositorio-GitHub\Lscm_Analise_de_Dados\Atv2_TODO\Tabela 1.1.1.xls"

In [ ]:
#Acessando as informações da Tabela--------------------------------------------------------
#header = None --> tira o nome da tabela
#os numeros exibidos são os nomes de cada coluna, elas devem ser renomeadas manualmente
tbBruta = pd.read_excel(caminho,engine='xlrd',header=None)
tbBruta

In [36]:
#Questão 1--------------------------------------------------------------------------------
bruto = pd.read_excel(caminho,engine="xlrd",header=None)
indicador_1 = bruto.iloc[8:40] #Determinando as linhas que serão vistas
#Renomeando as colunas
indicador_1.columns = [
    "Estado",
    "Total TODOS",
    "Total(H-M) Brancas",
    "Total(H-M) Preta/Parda",
    "Homen Branco",
    "Homem Preto/Pardo",
    "Mulher Branca",
    "Mulher Preta/Parda"
]
# Transformando horas em valores numericos para fazer calculo
#pois a table que vemos é em texto
for col in indicador_1.columns[1:]:
    indicador_1[col] = pd.to_numeric(indicador_1[col], errors="coerce")


#fazendo o calculo:
#criando a coluna que caula a diferença
indicador_1['Diferença horas trabalhadas M-PP M-B'] = indicador_1['Mulher Preta/Parda'] - indicador_1["Mulher Branca"]
#Agora devo exibir isso apenas considerando MG
indicador_1.loc[[28],"Mulher Branca":"Diferença horas trabalhadas M-PP M-B"]

    Mulher Branca  Mulher Preta/Parda  Diferença horas trabalhadas M-PP M-B
28       22.18665           23.075751                              0.889101

In [ ]:
#Questão 2--------------------------------------------------------------------------------
#Quantas horas mulheres pretas trabalham a mais que homens brancos no Brasil?
indicador_2 = pd.read_excel(caminho,engine="xlrd",header=None)
indicador_2.columns = [
    "Estado",
    "Total TODOS",
    "Total(H-M) Brancas",
    "Total(H-M) Preta/Parda",
    "Homen Branco",
    "Homem Preto/Pardo",
    "Mulher Branca",
    "Mulher Preta/Parda"
]
# Transformando horas em valores numericos para fazer calculo
#pois a table que vemos é em texto
for col in indicador_2.columns[1:]:
    indicador_2[col] = pd.to_numeric(indicador_2[col], errors="coerce")

#criando coluna de quantas horas a mais mulheres trabalham em comparação a homens brancos no brasil
indicador_2["Diferença Mullheres PP pra Homens B"] = indicador_2["Mulher Preta/Parda"] - indicador_2["Homen Branco"]
#Exibindo Resultados
indicador_2.loc[[8],["Homen Branco","Mulher Preta/Parda","Diferença Mullheres PP pra Homens B"]]

   Homen Branco  Mulher Preta/Parda  Diferença Mullheres PP pra Homens B
8     11.705136           22.037998                            10.332862