Agora responda:
- Quantas horas mulheres pretas trabalham a mais que mulheres brancas em Minas Gerais?(FEITO)
- Quantas horas mulheres pretas trabalham a mais que homens brancos no Brasil?(FEITO)
- Quantas horas mulheres pretas trabalham a mais que mulheres brancas no Amapá?(FEITO)
- Quantas horas mulheres pretas trabalham a mais que mulheres brancas no Paraná?(FEITO)
- Quantas horas mulheres pretas trabalham a mais que mulheres brancas por região?(FEITO)

In [3]:
# No terminal, uma vez: python -m pip install xlrd pandas
import pandas as pd

caminho = r"H:\Escola\Pytom(Jenaina)\Repositorio-GitHub\Lscm_Analise_de_Dados\Atv2_TODO\Tabela 1.1.1.xls"

In [19]:
#Acessando as informações da Tabela--------------------------------------------------------
#header = None --> tira o nome da tabela
#os numeros exibidos são os nomes de cada coluna, elas devem ser renomeadas manualmente
tbBruta = pd.read_excel(caminho,engine='xlrd',header=None)
tbBruta

,0,1,2,3,4,5,6,7
0,Tabela 1.1.1 - Número médio de horas semanais ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Grandes Regiões e Unidades da Federação,Número médio de horas semanais dedicadas aos c...,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,Total,Por sexo e cor ou raça,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,Total,NaN,Homem,NaN,Mulher,NaN
7,NaN,NaN,Branca,Preta ou parda,Branca,Preta ou parda,Branca,Preta ou parda
8,Brasil,16.985781,16.54593,17.333142,11.705136,11.74633,20.404106,22.037998
9,Norte,16.187037,15.925246,16.256032,11.588653,11.514646,19.29578,20.534188
10,Rondônia,17.014162,16.727733,17.101523,12.111127,12.54408,20.412887,21.06141
11,Acre,13.606903,13.806929,13.541399,10.79612,9.686983,16.130352,16.710754
12,Amazonas,16.80729,15.987545,16.995493,12.233043,12.822584,18.764969,20.716986
13,Roraima,13.639257,13.651755,13.633606,10.814803,10.476601,16.135877,16.560244
14,Pará,16.474268,16.181627,16.560239,11.524306,11.026707,19.83511,21.591144
15,Amapá,13.586656,14.38918,13.415091,11.116821,10.749444,16.648579,15.908487
16,Tocantins,15.815781,15.701788,15.768728,10.733863,11.682616,19.663713,19.629399
17,Nordeste,18.499396,18.1517,18.610911,11.723907,11.848436,22.744666,23.716716
18,Maranhão,16.669614,16.421773,16.708894,11.665173,11.437359,19.881056,20.739589
19,Piauí,17.960366,16.948094,18.231789,12.258324,11.204814,20.494063,23.69544
20,Ceará,19.499293,18.52712,19.882469,12.186936,12.821323,23.019718,24.952274
21,Rio Grande do Norte,18.30774,18.101853,18.445218,11.166909,11.086286,23.54708,24.422884
22,Paraíba,18.920816,18.88792,18.945306,12.480204,12.400831,23.642936,24.03565
23,Pernambuco,19.306249,18.950219,19.418444,12.312833,12.868821,23.35788,24.243396
24,Alagoas,20.217129,19.165111,20.560451,12.121839,13.35716,24.093655,25.856637
25,Sergipe,18.826541,17.264294,19.317934,10.830511,11.270341,21.740902,25.637681
26,Bahia,17.849776,17.538007,17.935566,10.551673,10.982808,22.57273,23.217119
27,Sudeste,17.104218,16.834863,17.397989,11.933522,12.180843,20.732969,21.990431
28,Minas Gerais,17.502141,17.179387,17.707564,11.31972,11.61912,22.18665,23.075751
29,Espírito Santo,17.111106,16.51061,17.478861,11.798571,12.017589,20.464462,22.196626
30,Rio de Janeiro,16.716263,16.097467,17.24306,12.000036,12.864896,19.203741,20.957728
31,São Paulo,17.071295,16.964437,17.25548,12.123044,12.2352,20.771186,21.76762
32,Sul,15.527769,15.570983,15.406088,11.546629,11.159487,19.012969,19.338734
33,Paraná,15.390122,15.453295,15.307289,11.240085,10.815611,18.896661,19.36538
34,Santa Catarina,16.039355,16.124417,15.616235,12.339052,11.517342,19.414764,19.646573
35,Rio Grande do Sul,15.356709,15.337269,15.448203,11.308447,11.519941,18.86823,19.10772
36,Centro-Oeste,15.000763,14.826985,15.078025,10.546799,10.332059,18.220683,19.33104
37,Mato Grosso do Sul,15.309783,14.902105,15.567204,10.446213,11.12692,18.5932,19.542761
38,Mato Grosso,14.239989,14.083513,14.270209,9.479654,9.265734,17.782825,18.695923
39,Goiás,15.186471,14.962622,15.296966,10.636424,10.531883,18.440842,19.587913
40,Distrito Federal,15.096351,15.061306,15.126295,11.377952,10.481279,17.738123,19.307332
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Fonte: IBGE. Pesquisa Nacional por Amostra de ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,Notas:,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,(1) Calculado apenas para as pessoas que decla...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,(2) Exclusive as pessoas sem declaração das ho...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
#Questão 1--------------------------------------------------------------------------------
bruto = pd.read_excel(caminho,engine="xlrd",header=None)
indicador_1 = bruto.iloc[8:40] #Determinando as linhas que serão vistas
#Renomeando as colunas
indicador_1.columns = [
    "Estado",
    "Total TODOS",
    "Total(H-M) Brancas",
    "Total(H-M) Preta/Parda",
    "Homen Branco",
    "Homem Preto/Pardo",
    "Mulher Branca",
    "Mulher Preta/Parda"
]
# Transformando horas em valores numericos para fazer calculo
#pois a table que vemos é em texto
for col in indicador_1.columns[1:]:
    indicador_1[col] = pd.to_numeric(indicador_1[col], errors="coerce")


#fazendo o calculo:
#criando a coluna que caula a diferença
indicador_1['Diferença horas trabalhadas M-PP M-B'] = indicador_1['Mulher Preta/Parda'] - indicador_1["Mulher Branca"]
#Agora devo exibir isso apenas considerando MG
indicador_1.loc[[28],["Estado","Mulher Branca","Mulher Preta/Parda","Diferença horas trabalhadas M-PP M-B"]]

,Estado,Mulher Branca,Mulher Preta/Parda,Diferença horas trabalhadas M-PP M-B
28,Minas Gerais,22.18665,23.075751,0.889101

In [24]:
#Questão 2--------------------------------------------------------------------------------
#Quantas horas mulheres pretas trabalham a mais que homens brancos no Brasil?
indicador_2 = pd.read_excel(caminho,engine="xlrd",header=None)
indicador_2.columns = [
    "Estado",
    "Total TODOS",
    "Total(H-M) Brancas",
    "Total(H-M) Preta/Parda",
    "Homen Branco",
    "Homem Preto/Pardo",
    "Mulher Branca",
    "Mulher Preta/Parda"
]
# Transformando horas em valores numericos para fazer calculo
#pois a table que vemos é em texto
for col in indicador_2.columns[1:]:
    indicador_2[col] = pd.to_numeric(indicador_2[col], errors="coerce")

#criando coluna de quantas horas a mais mulheres trabalham em comparação a homens brancos no brasil
indicador_2["Diferença Mullheres PP pra Homens B"] = indicador_2["Mulher Preta/Parda"] - indicador_2["Homen Branco"]
#Exibindo Resultados
indicador_2.loc[[8],["Estado","Homen Branco","Mulher Preta/Parda","Diferença Mullheres PP pra Homens B"]]

,Estado,Homen Branco,Mulher Preta/Parda,Diferença Mullheres PP pra Homens B
8,Brasil,11.705136,22.037998,10.332862

In [33]:
#Questão 3--------------------------------------------------------------------------------
#Quantas horas mulheres pretas trabalham a mais que mulheres brancas no Amapá?
indicador_3 = pd.read_excel(caminho,engine="xlrd",header=None)
indicador_3.columns = [
    "Estado",
    "Total TODOS",
    "Total(H-M) Brancas",
    "Total(H-M) Preta/Parda",
    "Homen Branco",
    "Homem Preto/Pardo",
    "Mulher Branca",
    "Mulher Preta/Parda"
]
# Transformando horas em valores numericos para fazer calculo
# pois a table que vemos é em texto
for col in indicador_3.columns[1:]:
   indicador_3[col] = pd.to_numeric(indicador_3[col], errors="coerce")

# Criando coluna de diferença
indicador_3["Diferença Mulheres PP pra Mulheres B Amapá"] = indicador_3["Mulher Branca"]- indicador_3["Mulher Preta/Parda"] 
#Exibindo Resultado
indicador_3.loc[[15],["Estado","Mulher Branca","Mulher Preta/Parda","Diferença Mulheres PP pra Mulheres B Amapá"]]

,Estado,Mulher Branca,Mulher Preta/Parda,Diferença Mulheres PP pra Mulheres B Amapá
15,Amapá,16.648579,15.908487,0.740092

In [36]:
#Questão 4--------------------------------------------------------------------------------
#Quantas horas mulheres pretas trabalham a mais que mulheres brancas no Paraná?
indicador_4 = pd.read_excel(caminho,engine="xlrd",header=None)
indicador_4.columns = [
    "Estado",
    "Total TODOS",
    "Total(H-M) Brancas",
    "Total(H-M) Preta/Parda",
    "Homen Branco",
    "Homem Preto/Pardo",
    "Mulher Branca",
    "Mulher Preta/Parda"
]
# Transformando horas em valores numericos para fazer calculo
# pois a table que vemos é em texto
for col in indicador_4.columns[1:]:
   indicador_4[col] = pd.to_numeric(indicador_4[col], errors="coerce")

# Criando coluna de diferença
indicador_4["Diferença Mulheres PP pra Mulheres B Paraná"] = indicador_4["Mulher Preta/Parda"] - indicador_4["Mulher Branca"]
#Exibindo Resultado
indicador_4.loc[[33],["Estado","Mulher Branca","Mulher Preta/Parda","Diferença Mulheres PP pra Mulheres B Paraná"]]

,Estado,Mulher Branca,Mulher Preta/Parda,Diferença Mulheres PP pra Mulheres B Paraná
33,Paraná,18.896661,19.36538,0.468719

In [43]:
# Questão 5--------------------------------------------------------------------------------
# Quantas horas mulheres pretas trabalham a mais que mulheres brancas por região?
indicador_5 = pd.read_excel(caminho,engine="xlrd",header=None)
indicador_5.columns = [
    "Estado",
    "Total TODOS",
    "Total(H-M) Brancas",
    "Total(H-M) Preta/Parda",
    "Homen Branco",
    "Homem Preto/Pardo",
    "Mulher Branca",
    "Mulher Preta/Parda"
]
# Transformando horas em valores numericos para fazer calculo
# pois a table que vemos é em texto
for col in indicador_5.columns[1:]:
   indicador_5[col] = pd.to_numeric(indicador_5[col], errors="coerce")

# Criando coluna de diferença
indicador_5["Diferença Mulheres PP e Mulheres B por Região"] = indicador_5["Mulher Preta/Parda"] - indicador_5["Mulher Branca"]
indicador_5.loc[8:40, ["Estado", "Mulher Branca", "Mulher Preta/Parda", "Diferença Mulheres PP e Mulheres B por Região"]]

,Estado,Mulher Branca,Mulher Preta/Parda,Diferença Mulheres PP e Mulheres B por Região
8,Brasil,20.404106,22.037998,1.633891
9,Norte,19.295780,20.534188,1.238408
10,Rondônia,20.412887,21.061410,0.648522
11,Acre,16.130352,16.710754,0.580402
12,Amazonas,18.764969,20.716986,1.952017
13,Roraima,16.135877,16.560244,0.424367
14,Pará,19.835110,21.591144,1.756034
15,Amapá,16.648579,15.908487,-0.740092
16,Tocantins,19.663713,19.629399,-0.034314
17,Nordeste,22.744666,23.716716,0.972050
18,Maranhão,19.881056,20.739589,0.858534
19,Piauí,20.494063,23.695440,3.201377
20,Ceará,23.019718,24.952274,1.932556
21,Rio Grande do Norte,23.547080,24.422884,0.875804
22,Paraíba,23.642936,24.035650,0.392714
23,Pernambuco,23.357880,24.243396,0.885517
24,Alagoas,24.093655,25.856637,1.762982
25,Sergipe,21.740902,25.637681,3.896779
26,Bahia,22.572730,23.217119,0.644388
27,Sudeste,20.732969,21.990431,1.257462
28,Minas Gerais,22.186650,23.075751,0.889101
29,Espírito Santo,20.464462,22.196626,1.732164
30,Rio de Janeiro,19.203741,20.957728,1.753987
31,São Paulo,20.771186,21.767620,0.996434
32,Sul,19.012969,19.338734,0.325765
33,Paraná,18.896661,19.365380,0.468719
34,Santa Catarina,19.414764,19.646573,0.231808
35,Rio Grande do Sul,18.868230,19.107720,0.239490
36,Centro-Oeste,18.220683,19.331040,1.110357
37,Mato Grosso do Sul,18.593200,19.542761,0.949560
38,Mato Grosso,17.782825,18.695923,0.913098
39,Goiás,18.440842,19.587913,1.147071
40,Distrito Federal,17.738123,19.307332,1.569209